### PR TITLE
Merge jdk8u302 ga

### PR DESCRIPTION
**Pull request by joeyleeeeeee97**

### CODE REVIEW

**Review by kelthuzadx — APPROVED** [review]

**Comment by joeyleeeeeee97** [comment]
image

**Comment by joeyleeeeeee97** [comment]
```

template <class FreeList_t>
class FreeListClosure : public StackObj {
  public:
    virtual void do_list(FreeList_t* fl) = 0;
};
template <class Chunk_t, class FreeList_t>
size_t TreeChunk<Chunk_t, FreeList_t>::_min_tree_chunk_size = sizeof(TreeChunk<Chunk_t, FreeList_t>)/HeapWordSize;
template <class Chunk_t, class FreeList_t>
size_t TreeChunk<Chunk_t, FreeList_t>::min_size() { return _min_tree_chunk_size; }
```

**Comment by joeyleeeeeee97** [comment]
<<<<<<<
  // lr could be poisoned with PAC signature during throw_pending_exception
  // if it was tail-call optimized by compiler, since lr is not callee-saved
  // reload it with proper value
  adr(lr, l);
=======
  if (EnableCoroutine) {
    // only if the entry_point is equal to `Interpreter::monitorenter()` will we do this amendment.
    if (entry_point == monitorenter_address_interp) {
      WISP_V2v_UPDATE;
    }
  }
>>>>>>>

**Comment by joeyleeeeeee97** [comment]
image

**Review by tanghaoth90 — APPROVED** [review]
lgtm

**Pull request merged**
